// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package nl.g4d.homemaps.car

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object CarApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * What the maneuver is, grouped like the phone's icons. Native maps this to
 * its own maneuver type; the icon itself comes from Dart (see registerImage).
 */
enum class CarManeuverType(val raw: Int) {
  DEPART(0),
  DESTINATION(1),
  DESTINATION_LEFT(2),
  DESTINATION_RIGHT(3),
  STRAIGHT(4),
  NAME_CHANGE(5),
  SLIGHT_RIGHT(6),
  RIGHT(7),
  SHARP_RIGHT(8),
  UTURN_RIGHT(9),
  UTURN_LEFT(10),
  SHARP_LEFT(11),
  LEFT(12),
  SLIGHT_LEFT(13),
  ON_RAMP_STRAIGHT(14),
  ON_RAMP_RIGHT(15),
  ON_RAMP_LEFT(16),
  OFF_RAMP_RIGHT(17),
  OFF_RAMP_LEFT(18),
  KEEP_STRAIGHT(19),
  KEEP_RIGHT(20),
  KEEP_LEFT(21),
  MERGE(22),
  MERGE_RIGHT(23),
  MERGE_LEFT(24),
  ROUNDABOUT(25),
  ROUNDABOUT_EXIT(26),
  FERRY_ENTER(27),
  FERRY_EXIT(28);

  companion object {
    fun ofRaw(raw: Int): CarManeuverType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A destination to pick: home, work, a recent one or a search result.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CarPlace (
  /** Dart's key for [CarFlutterApi.placeChosen]. */
  val id: String,
  val label: String,
  val detail: String,
  val lat: Double,
  val lon: Double,
  /** `home`, `work`, `recent` or `search`. */
  val kind: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarPlace {
      val id = pigeonVar_list[0] as String
      val label = pigeonVar_list[1] as String
      val detail = pigeonVar_list[2] as String
      val lat = pigeonVar_list[3] as Double
      val lon = pigeonVar_list[4] as Double
      val kind = pigeonVar_list[5] as String
      return CarPlace(id, label, detail, lat, lon, kind)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      label,
      detail,
      lat,
      lon,
      kind,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarPlace
    return CarApiPigeonUtils.deepEquals(this.id, other.id) && CarApiPigeonUtils.deepEquals(this.label, other.label) && CarApiPigeonUtils.deepEquals(this.detail, other.detail) && CarApiPigeonUtils.deepEquals(this.lat, other.lat) && CarApiPigeonUtils.deepEquals(this.lon, other.lon) && CarApiPigeonUtils.deepEquals(this.kind, other.kind)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.id)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.label)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.detail)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.lat)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.lon)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.kind)
    return result
  }
  override fun toString(): String {
    return "CarPlace(id=$id, label=$label, detail=$detail, lat=$lat, lon=$lon, kind=$kind)"
  }
}

/**
 * One route to choose from in the preview.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CarRouteSummary (
  val index: Long,
  /** "via A12, A27", or empty. */
  val via: String,
  val meters: Double,
  val seconds: Double,
  /** Extra time because of traffic, 0 if none. */
  val delaySeconds: Double,
  val hasToll: Boolean,
  val hasFerry: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarRouteSummary {
      val index = pigeonVar_list[0] as Long
      val via = pigeonVar_list[1] as String
      val meters = pigeonVar_list[2] as Double
      val seconds = pigeonVar_list[3] as Double
      val delaySeconds = pigeonVar_list[4] as Double
      val hasToll = pigeonVar_list[5] as Boolean
      val hasFerry = pigeonVar_list[6] as Boolean
      return CarRouteSummary(index, via, meters, seconds, delaySeconds, hasToll, hasFerry)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      index,
      via,
      meters,
      seconds,
      delaySeconds,
      hasToll,
      hasFerry,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarRouteSummary
    return CarApiPigeonUtils.deepEquals(this.index, other.index) && CarApiPigeonUtils.deepEquals(this.via, other.via) && CarApiPigeonUtils.deepEquals(this.meters, other.meters) && CarApiPigeonUtils.deepEquals(this.seconds, other.seconds) && CarApiPigeonUtils.deepEquals(this.delaySeconds, other.delaySeconds) && CarApiPigeonUtils.deepEquals(this.hasToll, other.hasToll) && CarApiPigeonUtils.deepEquals(this.hasFerry, other.hasFerry)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.index)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.via)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.meters)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.seconds)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.delaySeconds)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.hasToll)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.hasFerry)
    return result
  }
  override fun toString(): String {
    return "CarRouteSummary(index=$index, via=$via, meters=$meters, seconds=$seconds, delaySeconds=$delaySeconds, hasToll=$hasToll, hasFerry=$hasFerry)"
  }
}

/**
 * The sign at an exit: number, road numbers and directions.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CarRoadSign (
  val exit: String? = null,
  val roads: List<String>,
  val directions: List<String>,
  val label: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarRoadSign {
      val exit = pigeonVar_list[0] as String?
      val roads = pigeonVar_list[1] as List<String>
      val directions = pigeonVar_list[2] as List<String>
      val label = pigeonVar_list[3] as String?
      return CarRoadSign(exit, roads, directions, label)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      exit,
      roads,
      directions,
      label,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarRoadSign
    return CarApiPigeonUtils.deepEquals(this.exit, other.exit) && CarApiPigeonUtils.deepEquals(this.roads, other.roads) && CarApiPigeonUtils.deepEquals(this.directions, other.directions) && CarApiPigeonUtils.deepEquals(this.label, other.label)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.exit)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.roads)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.directions)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.label)
    return result
  }
  override fun toString(): String {
    return "CarRoadSign(exit=$exit, roads=$roads, directions=$directions, label=$label)"
  }
}

/**
 * One lane, as OSRM names the directions ("left", "slight right", ...).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CarLane (
  val directions: List<String>,
  /** This lane is one you can use for the maneuver. */
  val correct: Boolean,
  /** The direction you take in this lane, if it is a correct one. */
  val usage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarLane {
      val directions = pigeonVar_list[0] as List<String>
      val correct = pigeonVar_list[1] as Boolean
      val usage = pigeonVar_list[2] as String?
      return CarLane(directions, correct, usage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      directions,
      correct,
      usage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarLane
    return CarApiPigeonUtils.deepEquals(this.directions, other.directions) && CarApiPigeonUtils.deepEquals(this.correct, other.correct) && CarApiPigeonUtils.deepEquals(this.usage, other.usage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.directions)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.correct)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.usage)
    return result
  }
  override fun toString(): String {
    return "CarLane(directions=$directions, correct=$correct, usage=$usage)"
  }
}

/**
 * The next maneuver, as the car shows it.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CarManeuver (
  val type: CarManeuverType,
  /** The full sentence ("Turn right onto Main Street"). */
  val instruction: String,
  /** Briefly what you do at a ramp or fork ("Keep left"), or null. */
  val shortAction: String? = null,
  val streets: List<String>,
  val roundaboutExit: Long? = null,
  /** Where you leave the roundabout, clockwise from straight on (degrees). */
  val roundaboutAngle: Double? = null,
  val sign: CarRoadSign? = null,
  /**
   * The sign as an image (shields and directions, as the phone's panel),
   * registered earlier; null without a sign.
   */
  val signIconKey: String? = null,
  /** An image registered earlier with [CarHostApi.registerImage]. */
  val iconKey: String,
  /** Already rounded so it doesn't change every meter. */
  val metersToNext: Double,
  /**
   * The maneuver right after this one, if it follows within a few hundred
   * meters: at most one. (A list, not a nullable field: Swift structs can't
   * contain themselves.)
   */
  val then: List<CarManeuver>,
  val lanes: List<CarLane>? = null,
  /** The lane bar as an image, registered earlier. */
  val lanesIconKey: String? = null,
  /** How far the lanes' junction is, if that isn't the maneuver itself. */
  val lanesAhead: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarManeuver {
      val type = pigeonVar_list[0] as CarManeuverType
      val instruction = pigeonVar_list[1] as String
      val shortAction = pigeonVar_list[2] as String?
      val streets = pigeonVar_list[3] as List<String>
      val roundaboutExit = pigeonVar_list[4] as Long?
      val roundaboutAngle = pigeonVar_list[5] as Double?
      val sign = pigeonVar_list[6] as CarRoadSign?
      val signIconKey = pigeonVar_list[7] as String?
      val iconKey = pigeonVar_list[8] as String
      val metersToNext = pigeonVar_list[9] as Double
      val then = pigeonVar_list[10] as List<CarManeuver>
      val lanes = pigeonVar_list[11] as List<CarLane>?
      val lanesIconKey = pigeonVar_list[12] as String?
      val lanesAhead = pigeonVar_list[13] as Double?
      return CarManeuver(type, instruction, shortAction, streets, roundaboutExit, roundaboutAngle, sign, signIconKey, iconKey, metersToNext, then, lanes, lanesIconKey, lanesAhead)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      instruction,
      shortAction,
      streets,
      roundaboutExit,
      roundaboutAngle,
      sign,
      signIconKey,
      iconKey,
      metersToNext,
      then,
      lanes,
      lanesIconKey,
      lanesAhead,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarManeuver
    return CarApiPigeonUtils.deepEquals(this.type, other.type) && CarApiPigeonUtils.deepEquals(this.instruction, other.instruction) && CarApiPigeonUtils.deepEquals(this.shortAction, other.shortAction) && CarApiPigeonUtils.deepEquals(this.streets, other.streets) && CarApiPigeonUtils.deepEquals(this.roundaboutExit, other.roundaboutExit) && CarApiPigeonUtils.deepEquals(this.roundaboutAngle, other.roundaboutAngle) && CarApiPigeonUtils.deepEquals(this.sign, other.sign) && CarApiPigeonUtils.deepEquals(this.signIconKey, other.signIconKey) && CarApiPigeonUtils.deepEquals(this.iconKey, other.iconKey) && CarApiPigeonUtils.deepEquals(this.metersToNext, other.metersToNext) && CarApiPigeonUtils.deepEquals(this.then, other.then) && CarApiPigeonUtils.deepEquals(this.lanes, other.lanes) && CarApiPigeonUtils.deepEquals(this.lanesIconKey, other.lanesIconKey) && CarApiPigeonUtils.deepEquals(this.lanesAhead, other.lanesAhead)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.type)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.instruction)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.shortAction)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.streets)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.roundaboutExit)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.roundaboutAngle)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.sign)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.signIconKey)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.iconKey)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.metersToNext)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.then)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.lanes)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.lanesIconKey)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.lanesAhead)
    return result
  }
  override fun toString(): String {
    return "CarManeuver(type=$type, instruction=$instruction, shortAction=$shortAction, streets=$streets, roundaboutExit=$roundaboutExit, roundaboutAngle=$roundaboutAngle, sign=$sign, signIconKey=$signIconKey, iconKey=$iconKey, metersToNext=$metersToNext, then=$then, lanes=$lanes, lanesIconKey=$lanesIconKey, lanesAhead=$lanesAhead)"
  }
}

/**
 * The trip as a whole: where to, how far, how long.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CarTrip (
  val destinationLabel: String,
  val remainingMeters: Double,
  val remainingSeconds: Double,
  val etaEpochMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarTrip {
      val destinationLabel = pigeonVar_list[0] as String
      val remainingMeters = pigeonVar_list[1] as Double
      val remainingSeconds = pigeonVar_list[2] as Double
      val etaEpochMs = pigeonVar_list[3] as Long
      return CarTrip(destinationLabel, remainingMeters, remainingSeconds, etaEpochMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      destinationLabel,
      remainingMeters,
      remainingSeconds,
      etaEpochMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarTrip
    return CarApiPigeonUtils.deepEquals(this.destinationLabel, other.destinationLabel) && CarApiPigeonUtils.deepEquals(this.remainingMeters, other.remainingMeters) && CarApiPigeonUtils.deepEquals(this.remainingSeconds, other.remainingSeconds) && CarApiPigeonUtils.deepEquals(this.etaEpochMs, other.etaEpochMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.destinationLabel)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.remainingMeters)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.remainingSeconds)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.etaEpochMs)
    return result
  }
  override fun toString(): String {
    return "CarTrip(destinationLabel=$destinationLabel, remainingMeters=$remainingMeters, remainingSeconds=$remainingSeconds, etaEpochMs=$etaEpochMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CarSpeed (
  val limitKmh: Long? = null,
  /** `osm`, `timeOfDay`, `roadworks` or `msi` (a red ring). */
  val limitSource: String,
  val speedMs: Double? = null,
  /**
   * Above the speed limit: the next speed camera or the average speed check
   * you're in. The icon (see [CarHostApi.registerImage]) and its text ("400
   * m", "avg 97"), with a smaller line below ("2.3 km to go"); null if
   * there's none.
   */
  val cameraIconKey: String? = null,
  val cameraText: String? = null,
  val cameraDetail: String? = null,
  /** Your average in the section is above its limit: the sign goes red. */
  val cameraOver: Boolean,
  /**
   * The next gantry's matrix signs (MSI) as one image, registered earlier;
   * null when there is none ahead. Shown where the lanes go, instead of them.
   */
  val matrixIconKey: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarSpeed {
      val limitKmh = pigeonVar_list[0] as Long?
      val limitSource = pigeonVar_list[1] as String
      val speedMs = pigeonVar_list[2] as Double?
      val cameraIconKey = pigeonVar_list[3] as String?
      val cameraText = pigeonVar_list[4] as String?
      val cameraDetail = pigeonVar_list[5] as String?
      val cameraOver = pigeonVar_list[6] as Boolean
      val matrixIconKey = pigeonVar_list[7] as String?
      return CarSpeed(limitKmh, limitSource, speedMs, cameraIconKey, cameraText, cameraDetail, cameraOver, matrixIconKey)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      limitKmh,
      limitSource,
      speedMs,
      cameraIconKey,
      cameraText,
      cameraDetail,
      cameraOver,
      matrixIconKey,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarSpeed
    return CarApiPigeonUtils.deepEquals(this.limitKmh, other.limitKmh) && CarApiPigeonUtils.deepEquals(this.limitSource, other.limitSource) && CarApiPigeonUtils.deepEquals(this.speedMs, other.speedMs) && CarApiPigeonUtils.deepEquals(this.cameraIconKey, other.cameraIconKey) && CarApiPigeonUtils.deepEquals(this.cameraText, other.cameraText) && CarApiPigeonUtils.deepEquals(this.cameraDetail, other.cameraDetail) && CarApiPigeonUtils.deepEquals(this.cameraOver, other.cameraOver) && CarApiPigeonUtils.deepEquals(this.matrixIconKey, other.matrixIconKey)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.limitKmh)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.limitSource)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.speedMs)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.cameraIconKey)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.cameraText)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.cameraDetail)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.cameraOver)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.matrixIconKey)
    return result
  }
  override fun toString(): String {
    return "CarSpeed(limitKmh=$limitKmh, limitSource=$limitSource, speedMs=$speedMs, cameraIconKey=$cameraIconKey, cameraText=$cameraText, cameraDetail=$cameraDetail, cameraOver=$cameraOver, matrixIconKey=$matrixIconKey)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CarPosition (
  val lat: Double,
  val lon: Double,
  val heading: Double? = null,
  val speed: Double? = null,
  val accuracy: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarPosition {
      val lat = pigeonVar_list[0] as Double
      val lon = pigeonVar_list[1] as Double
      val heading = pigeonVar_list[2] as Double?
      val speed = pigeonVar_list[3] as Double?
      val accuracy = pigeonVar_list[4] as Double
      return CarPosition(lat, lon, heading, speed, accuracy)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lat,
      lon,
      heading,
      speed,
      accuracy,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarPosition
    return CarApiPigeonUtils.deepEquals(this.lat, other.lat) && CarApiPigeonUtils.deepEquals(this.lon, other.lon) && CarApiPigeonUtils.deepEquals(this.heading, other.heading) && CarApiPigeonUtils.deepEquals(this.speed, other.speed) && CarApiPigeonUtils.deepEquals(this.accuracy, other.accuracy)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.lat)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.lon)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.heading)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.speed)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.accuracy)
    return result
  }
  override fun toString(): String {
    return "CarPosition(lat=$lat, lon=$lon, heading=$heading, speed=$speed, accuracy=$accuracy)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CarCamera (
  val lat: Double,
  val lon: Double,
  val zoom: Double,
  val bearing: Double,
  val tilt: Double,
  val animateMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarCamera {
      val lat = pigeonVar_list[0] as Double
      val lon = pigeonVar_list[1] as Double
      val zoom = pigeonVar_list[2] as Double
      val bearing = pigeonVar_list[3] as Double
      val tilt = pigeonVar_list[4] as Double
      val animateMs = pigeonVar_list[5] as Long
      return CarCamera(lat, lon, zoom, bearing, tilt, animateMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lat,
      lon,
      zoom,
      bearing,
      tilt,
      animateMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarCamera
    return CarApiPigeonUtils.deepEquals(this.lat, other.lat) && CarApiPigeonUtils.deepEquals(this.lon, other.lon) && CarApiPigeonUtils.deepEquals(this.zoom, other.zoom) && CarApiPigeonUtils.deepEquals(this.bearing, other.bearing) && CarApiPigeonUtils.deepEquals(this.tilt, other.tilt) && CarApiPigeonUtils.deepEquals(this.animateMs, other.animateMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.lat)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.lon)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.zoom)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.bearing)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.tilt)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.animateMs)
    return result
  }
  override fun toString(): String {
    return "CarCamera(lat=$lat, lon=$lon, zoom=$zoom, bearing=$bearing, tilt=$tilt, animateMs=$animateMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CarBounds (
  val south: Double,
  val west: Double,
  val north: Double,
  val east: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarBounds {
      val south = pigeonVar_list[0] as Double
      val west = pigeonVar_list[1] as Double
      val north = pigeonVar_list[2] as Double
      val east = pigeonVar_list[3] as Double
      return CarBounds(south, west, north, east)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      south,
      west,
      north,
      east,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarBounds
    return CarApiPigeonUtils.deepEquals(this.south, other.south) && CarApiPigeonUtils.deepEquals(this.west, other.west) && CarApiPigeonUtils.deepEquals(this.north, other.north) && CarApiPigeonUtils.deepEquals(this.east, other.east)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.south)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.west)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.north)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.east)
    return result
  }
  override fun toString(): String {
    return "CarBounds(south=$south, west=$west, north=$north, east=$east)"
  }
}

/**
 * The car's screen.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CarSurface (
  val width: Double,
  val height: Double,
  val density: Double,
  val dark: Boolean,
  /** `androidauto` or `carplay`. */
  val platform: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarSurface {
      val width = pigeonVar_list[0] as Double
      val height = pigeonVar_list[1] as Double
      val density = pigeonVar_list[2] as Double
      val dark = pigeonVar_list[3] as Boolean
      val platform = pigeonVar_list[4] as String
      return CarSurface(width, height, density, dark, platform)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      width,
      height,
      density,
      dark,
      platform,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarSurface
    return CarApiPigeonUtils.deepEquals(this.width, other.width) && CarApiPigeonUtils.deepEquals(this.height, other.height) && CarApiPigeonUtils.deepEquals(this.density, other.density) && CarApiPigeonUtils.deepEquals(this.dark, other.dark) && CarApiPigeonUtils.deepEquals(this.platform, other.platform)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.width)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.height)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.density)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.dark)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.platform)
    return result
  }
  override fun toString(): String {
    return "CarSurface(width=$width, height=$height, density=$density, dark=$dark, platform=$platform)"
  }
}

/**
 * A question to the driver, like a faster route.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CarAlert (
  val id: String,
  val title: String,
  val text: String,
  val accept: String,
  val reject: String,
  /** After this it disappears by itself. */
  val seconds: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CarAlert {
      val id = pigeonVar_list[0] as String
      val title = pigeonVar_list[1] as String
      val text = pigeonVar_list[2] as String
      val accept = pigeonVar_list[3] as String
      val reject = pigeonVar_list[4] as String
      val seconds = pigeonVar_list[5] as Long
      return CarAlert(id, title, text, accept, reject, seconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      title,
      text,
      accept,
      reject,
      seconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CarAlert
    return CarApiPigeonUtils.deepEquals(this.id, other.id) && CarApiPigeonUtils.deepEquals(this.title, other.title) && CarApiPigeonUtils.deepEquals(this.text, other.text) && CarApiPigeonUtils.deepEquals(this.accept, other.accept) && CarApiPigeonUtils.deepEquals(this.reject, other.reject) && CarApiPigeonUtils.deepEquals(this.seconds, other.seconds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + CarApiPigeonUtils.deepHash(this.id)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.title)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.text)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.accept)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.reject)
    result = 31 * result + CarApiPigeonUtils.deepHash(this.seconds)
    return result
  }
  override fun toString(): String {
    return "CarAlert(id=$id, title=$title, text=$text, accept=$accept, reject=$reject, seconds=$seconds)"
  }
}
private open class CarApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CarManeuverType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarPlace.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarRouteSummary.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarRoadSign.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarLane.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarManeuver.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarTrip.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarSpeed.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarPosition.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarCamera.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarBounds.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarSurface.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CarAlert.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CarManeuverType -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is CarPlace -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CarRouteSummary -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CarRoadSign -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is CarLane -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is CarManeuver -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is CarTrip -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CarSpeed -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is CarPosition -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is CarCamera -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is CarBounds -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is CarSurface -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is CarAlert -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Dart to the car. Native ignores everything while no car is connected.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface CarHostApi {
  /**
   * Dart's handlers are in place; native replays a connection that happened
   * before this.
   */
  fun ready()
  /**
   * The labels of the templates in the user's language, by key (see
   * `CarBridge.texts`), so the translations stay in one place.
   */
  fun setTexts(texts: Map<String, String>)
  /**
   * The map style: a URL, or the style itself as JSON (the night version).
   * [dark]: it's a night style, so the map's backdrop is dark too.
   */
  fun setStyle(style: String, isJson: Boolean, dark: Boolean)
  /**
   * A PNG for the map (arrow head, location dot) or the templates (maneuver
   * and lane icons), by key. [scale] is the pixel ratio it was drawn at.
   */
  fun registerImage(key: String, png: ByteArray, scale: Double)
  /** GeoJSON feature collections, as the phone draws them. */
  fun setRoutes(geoJson: String)
  fun setDriven(geoJson: String)
  fun setArrow(geoJson: String)
  fun setPosition(position: CarPosition)
  /**
   * The camera during navigation: over the position, in the direction of
   * travel.
   */
  fun followCamera(camera: CarCamera)
  fun fitBounds(bounds: CarBounds, paddingPx: Double)
  /** Whether the camera follows; off after the user moved the map. */
  fun setFollowing(following: Boolean)
  /**
   * The start screen: pick where to go. [locationOk]: the phone has a fix;
   * otherwise the car asks for permission or tells the driver to open the
   * app.
   */
  fun showHome(favourites: List<CarPlace>, recents: List<CarPlace>, locationOk: Boolean)
  /** The routes to choose from, after a place was picked. */
  fun showRoutePreview(destinationLabel: String, routes: List<CarRouteSummary>, chosen: Long)
  fun showLoading(loading: Boolean)
  fun showMessage(title: String, text: String)
  fun startNavigation(trip: CarTrip)
  fun updateManeuver(next: CarManeuver, trip: CarTrip)
  /**
   * Your speed, the limit and what's ahead on the road: every fix on which
   * something of it changed, apart from the maneuver.
   */
  fun setSpeed(speed: CarSpeed)
  fun setRecalculating(recalculating: Boolean)
  fun showArrived(destinationLabel: String)
  fun endNavigation()
  fun setMuted(muted: Boolean)
  fun showAlert(alert: CarAlert)
  fun dismissAlert(id: String)

  companion object {
    /** The codec used by CarHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CarApiPigeonCodec()
    }
    /** Sets up an instance of `CarHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CarHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.ready$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.ready()
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.setTexts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textsArg = args[0] as Map<String, String>
            val wrapped: List<Any?> = try {
              api.setTexts(textsArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.setStyle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val styleArg = args[0] as String
            val isJsonArg = args[1] as Boolean
            val darkArg = args[2] as Boolean
            val wrapped: List<Any?> = try {
              api.setStyle(styleArg, isJsonArg, darkArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.registerImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val pngArg = args[1] as ByteArray
            val scaleArg = args[2] as Double
            val wrapped: List<Any?> = try {
              api.registerImage(keyArg, pngArg, scaleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.setRoutes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val geoJsonArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setRoutes(geoJsonArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.setDriven$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val geoJsonArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setDriven(geoJsonArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.setArrow$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val geoJsonArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.setArrow(geoJsonArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.setPosition$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val positionArg = args[0] as CarPosition
            val wrapped: List<Any?> = try {
              api.setPosition(positionArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.followCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cameraArg = args[0] as CarCamera
            val wrapped: List<Any?> = try {
              api.followCamera(cameraArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.fitBounds$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val boundsArg = args[0] as CarBounds
            val paddingPxArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.fitBounds(boundsArg, paddingPxArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.setFollowing$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val followingArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setFollowing(followingArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.showHome$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val favouritesArg = args[0] as List<CarPlace>
            val recentsArg = args[1] as List<CarPlace>
            val locationOkArg = args[2] as Boolean
            val wrapped: List<Any?> = try {
              api.showHome(favouritesArg, recentsArg, locationOkArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.showRoutePreview$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val destinationLabelArg = args[0] as String
            val routesArg = args[1] as List<CarRouteSummary>
            val chosenArg = args[2] as Long
            val wrapped: List<Any?> = try {
              api.showRoutePreview(destinationLabelArg, routesArg, chosenArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.showLoading$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val loadingArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.showLoading(loadingArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.showMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val titleArg = args[0] as String
            val textArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.showMessage(titleArg, textArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.startNavigation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tripArg = args[0] as CarTrip
            val wrapped: List<Any?> = try {
              api.startNavigation(tripArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.updateManeuver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nextArg = args[0] as CarManeuver
            val tripArg = args[1] as CarTrip
            val wrapped: List<Any?> = try {
              api.updateManeuver(nextArg, tripArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.setSpeed$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val speedArg = args[0] as CarSpeed
            val wrapped: List<Any?> = try {
              api.setSpeed(speedArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.setRecalculating$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recalculatingArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setRecalculating(recalculatingArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.showArrived$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val destinationLabelArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.showArrived(destinationLabelArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.endNavigation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.endNavigation()
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.setMuted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val mutedArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setMuted(mutedArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.showAlert$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val alertArg = args[0] as CarAlert
            val wrapped: List<Any?> = try {
              api.showAlert(alertArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.homemaps.CarHostApi.dismissAlert$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.dismissAlert(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              CarApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * The car to Dart: what the driver does.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class CarFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CarFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CarApiPigeonCodec()
    }
  }
  suspend fun connected(surfaceArg: CarSurface)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.connected$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(surfaceArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun disconnected()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.disconnected$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /** The screen size or dark mode changed. */
  suspend fun surfaceChanged(surfaceArg: CarSurface)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.surfaceChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(surfaceArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun placeChosen(idArg: String)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.placeChosen$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(idArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun search(textArg: String): List<CarPlace>
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.search$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(textArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else if (it[0] == null) {
            continuation.resumeWithException(FlutterError("null-error", "Flutter api returned null value for non-null return value.", ""))
          } else {
            val output = it[0] as List<CarPlace>
            continuation.resume(output)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun routeChosen(indexArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.routeChosen$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(indexArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun startTrip()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.startTrip$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun stopTrip()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.stopTrip$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun toggleMute()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.toggleMute$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /** The driver panned or zoomed: following stops. */
  suspend fun userMovedMap()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.userMovedMap$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun recenter()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.recenter$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun alertAnswered(idArg: String, acceptedArg: Boolean)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.alertAnswered$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(idArg, acceptedArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /**
   * Android's test drive (the review requires it): a fake GPS drives the
   * route.
   */
  suspend fun autoDriveEnabled()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.autoDriveEnabled$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /**
   * A `geo:` or navigation intent in the car: a point with a name, or a
   * search text.
   */
  suspend fun navigateTo(latArg: Double?, lonArg: Double?, labelArg: String?, queryArg: String?)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.navigateTo$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(latArg, lonArg, labelArg, queryArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  suspend fun backToHome()
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.homemaps.CarFlutterApi.backToHome$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(null) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(CarApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
