// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// What the maneuver is, grouped like the phone's icons. Native maps this to
/// its own maneuver type; the icon itself comes from Dart (see registerImage).
enum CarManeuverType {
  depart,
  destination,
  destinationLeft,
  destinationRight,
  straight,
  nameChange,
  slightRight,
  right,
  sharpRight,
  uturnRight,
  uturnLeft,
  sharpLeft,
  left,
  slightLeft,
  onRampStraight,
  onRampRight,
  onRampLeft,
  offRampRight,
  offRampLeft,
  keepStraight,
  keepRight,
  keepLeft,
  merge,
  mergeRight,
  mergeLeft,
  roundabout,
  roundaboutExit,
  ferryEnter,
  ferryExit,
}

/// A destination to pick: home, work, a recent one or a search result.
class CarPlace {
  CarPlace({
    required this.id,
    required this.label,
    required this.detail,
    required this.lat,
    required this.lon,
    required this.kind,
  });

  /// Dart's key for [CarFlutterApi.placeChosen].
  String id;

  String label;

  String detail;

  double lat;

  double lon;

  /// `home`, `work`, `recent` or `search`.
  String kind;

  List<Object?> _toList() {
    return <Object?>[id, label, detail, lat, lon, kind];
  }

  Object encode() {
    return _toList();
  }

  static CarPlace decode(Object result) {
    result as List<Object?>;
    return CarPlace(
      id: result[0]! as String,
      label: result[1]! as String,
      detail: result[2]! as String,
      lat: result[3]! as double,
      lon: result[4]! as double,
      kind: result[5]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarPlace || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(label, other.label) &&
        _deepEquals(detail, other.detail) &&
        _deepEquals(lat, other.lat) &&
        _deepEquals(lon, other.lon) &&
        _deepEquals(kind, other.kind);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarPlace(id: $id, label: $label, detail: $detail, lat: $lat, lon: $lon, kind: $kind)';
  }
}

/// One route to choose from in the preview.
class CarRouteSummary {
  CarRouteSummary({
    required this.index,
    required this.via,
    required this.meters,
    required this.seconds,
    required this.delaySeconds,
    required this.hasToll,
    required this.hasFerry,
  });

  int index;

  /// "via A12, A27", or empty.
  String via;

  double meters;

  double seconds;

  /// Extra time because of traffic, 0 if none.
  double delaySeconds;

  bool hasToll;

  bool hasFerry;

  List<Object?> _toList() {
    return <Object?>[
      index,
      via,
      meters,
      seconds,
      delaySeconds,
      hasToll,
      hasFerry,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CarRouteSummary decode(Object result) {
    result as List<Object?>;
    return CarRouteSummary(
      index: result[0]! as int,
      via: result[1]! as String,
      meters: result[2]! as double,
      seconds: result[3]! as double,
      delaySeconds: result[4]! as double,
      hasToll: result[5]! as bool,
      hasFerry: result[6]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarRouteSummary || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(index, other.index) &&
        _deepEquals(via, other.via) &&
        _deepEquals(meters, other.meters) &&
        _deepEquals(seconds, other.seconds) &&
        _deepEquals(delaySeconds, other.delaySeconds) &&
        _deepEquals(hasToll, other.hasToll) &&
        _deepEquals(hasFerry, other.hasFerry);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarRouteSummary(index: $index, via: $via, meters: $meters, seconds: $seconds, delaySeconds: $delaySeconds, hasToll: $hasToll, hasFerry: $hasFerry)';
  }
}

/// The sign at an exit: number, road numbers and directions.
class CarRoadSign {
  CarRoadSign({
    this.exit,
    required this.roads,
    required this.directions,
    this.label,
  });

  String? exit;

  List<String> roads;

  List<String> directions;

  String? label;

  List<Object?> _toList() {
    return <Object?>[exit, roads, directions, label];
  }

  Object encode() {
    return _toList();
  }

  static CarRoadSign decode(Object result) {
    result as List<Object?>;
    return CarRoadSign(
      exit: result[0] as String?,
      roads: (result[1]! as List<Object?>).cast<String>(),
      directions: (result[2]! as List<Object?>).cast<String>(),
      label: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarRoadSign || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(exit, other.exit) &&
        _deepEquals(roads, other.roads) &&
        _deepEquals(directions, other.directions) &&
        _deepEquals(label, other.label);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarRoadSign(exit: $exit, roads: $roads, directions: $directions, label: $label)';
  }
}

/// One lane, as OSRM names the directions ("left", "slight right", ...).
class CarLane {
  CarLane({required this.directions, required this.correct, this.usage});

  List<String> directions;

  /// This lane is one you can use for the maneuver.
  bool correct;

  /// The direction you take in this lane, if it is a correct one.
  String? usage;

  List<Object?> _toList() {
    return <Object?>[directions, correct, usage];
  }

  Object encode() {
    return _toList();
  }

  static CarLane decode(Object result) {
    result as List<Object?>;
    return CarLane(
      directions: (result[0]! as List<Object?>).cast<String>(),
      correct: result[1]! as bool,
      usage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarLane || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(directions, other.directions) &&
        _deepEquals(correct, other.correct) &&
        _deepEquals(usage, other.usage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarLane(directions: $directions, correct: $correct, usage: $usage)';
  }
}

/// The next maneuver, as the car shows it.
class CarManeuver {
  CarManeuver({
    required this.type,
    required this.instruction,
    this.shortAction,
    required this.streets,
    this.roundaboutExit,
    this.roundaboutAngle,
    this.sign,
    required this.iconKey,
    required this.metersToNext,
    this.then,
    this.lanes,
    this.lanesIconKey,
    this.lanesAhead,
  });

  CarManeuverType type;

  /// The full sentence ("Turn right onto Main Street").
  String instruction;

  /// Briefly what you do at a ramp or fork ("Keep left"), or null.
  String? shortAction;

  List<String> streets;

  int? roundaboutExit;

  /// Where you leave the roundabout, clockwise from straight on (degrees).
  double? roundaboutAngle;

  CarRoadSign? sign;

  /// An image registered earlier with [CarHostApi.registerImage].
  String iconKey;

  /// Already rounded so it doesn't change every meter.
  double metersToNext;

  /// The maneuver right after this one, if it follows within a few hundred
  /// meters.
  CarManeuver? then;

  List<CarLane>? lanes;

  /// The lane bar as an image, registered earlier.
  String? lanesIconKey;

  /// How far the lanes' junction is, if that isn't the maneuver itself.
  double? lanesAhead;

  List<Object?> _toList() {
    return <Object?>[
      type,
      instruction,
      shortAction,
      streets,
      roundaboutExit,
      roundaboutAngle,
      sign,
      iconKey,
      metersToNext,
      then,
      lanes,
      lanesIconKey,
      lanesAhead,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CarManeuver decode(Object result) {
    result as List<Object?>;
    return CarManeuver(
      type: result[0]! as CarManeuverType,
      instruction: result[1]! as String,
      shortAction: result[2] as String?,
      streets: (result[3]! as List<Object?>).cast<String>(),
      roundaboutExit: result[4] as int?,
      roundaboutAngle: result[5] as double?,
      sign: result[6] as CarRoadSign?,
      iconKey: result[7]! as String,
      metersToNext: result[8]! as double,
      then: result[9] as CarManeuver?,
      lanes: (result[10] as List<Object?>?)?.cast<CarLane>(),
      lanesIconKey: result[11] as String?,
      lanesAhead: result[12] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarManeuver || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(instruction, other.instruction) &&
        _deepEquals(shortAction, other.shortAction) &&
        _deepEquals(streets, other.streets) &&
        _deepEquals(roundaboutExit, other.roundaboutExit) &&
        _deepEquals(roundaboutAngle, other.roundaboutAngle) &&
        _deepEquals(sign, other.sign) &&
        _deepEquals(iconKey, other.iconKey) &&
        _deepEquals(metersToNext, other.metersToNext) &&
        _deepEquals(then, other.then) &&
        _deepEquals(lanes, other.lanes) &&
        _deepEquals(lanesIconKey, other.lanesIconKey) &&
        _deepEquals(lanesAhead, other.lanesAhead);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarManeuver(type: $type, instruction: $instruction, shortAction: $shortAction, streets: $streets, roundaboutExit: $roundaboutExit, roundaboutAngle: $roundaboutAngle, sign: $sign, iconKey: $iconKey, metersToNext: $metersToNext, then: $then, lanes: $lanes, lanesIconKey: $lanesIconKey, lanesAhead: $lanesAhead)';
  }
}

/// The trip as a whole: where to, how far, how long.
class CarTrip {
  CarTrip({
    required this.destinationLabel,
    required this.remainingMeters,
    required this.remainingSeconds,
    required this.etaEpochMs,
  });

  String destinationLabel;

  double remainingMeters;

  double remainingSeconds;

  int etaEpochMs;

  List<Object?> _toList() {
    return <Object?>[
      destinationLabel,
      remainingMeters,
      remainingSeconds,
      etaEpochMs,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CarTrip decode(Object result) {
    result as List<Object?>;
    return CarTrip(
      destinationLabel: result[0]! as String,
      remainingMeters: result[1]! as double,
      remainingSeconds: result[2]! as double,
      etaEpochMs: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarTrip || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(destinationLabel, other.destinationLabel) &&
        _deepEquals(remainingMeters, other.remainingMeters) &&
        _deepEquals(remainingSeconds, other.remainingSeconds) &&
        _deepEquals(etaEpochMs, other.etaEpochMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarTrip(destinationLabel: $destinationLabel, remainingMeters: $remainingMeters, remainingSeconds: $remainingSeconds, etaEpochMs: $etaEpochMs)';
  }
}

class CarSpeed {
  CarSpeed({this.limitKmh, required this.limitSource, this.speedMs});

  int? limitKmh;

  /// `osm`, `timeOfDay`, `roadworks` or `msi` (a red ring).
  String limitSource;

  double? speedMs;

  List<Object?> _toList() {
    return <Object?>[limitKmh, limitSource, speedMs];
  }

  Object encode() {
    return _toList();
  }

  static CarSpeed decode(Object result) {
    result as List<Object?>;
    return CarSpeed(
      limitKmh: result[0] as int?,
      limitSource: result[1]! as String,
      speedMs: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarSpeed || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(limitKmh, other.limitKmh) &&
        _deepEquals(limitSource, other.limitSource) &&
        _deepEquals(speedMs, other.speedMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarSpeed(limitKmh: $limitKmh, limitSource: $limitSource, speedMs: $speedMs)';
  }
}

class CarPosition {
  CarPosition({
    required this.lat,
    required this.lon,
    this.heading,
    this.speed,
    required this.accuracy,
  });

  double lat;

  double lon;

  double? heading;

  double? speed;

  double accuracy;

  List<Object?> _toList() {
    return <Object?>[lat, lon, heading, speed, accuracy];
  }

  Object encode() {
    return _toList();
  }

  static CarPosition decode(Object result) {
    result as List<Object?>;
    return CarPosition(
      lat: result[0]! as double,
      lon: result[1]! as double,
      heading: result[2] as double?,
      speed: result[3] as double?,
      accuracy: result[4]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarPosition || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(lat, other.lat) &&
        _deepEquals(lon, other.lon) &&
        _deepEquals(heading, other.heading) &&
        _deepEquals(speed, other.speed) &&
        _deepEquals(accuracy, other.accuracy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarPosition(lat: $lat, lon: $lon, heading: $heading, speed: $speed, accuracy: $accuracy)';
  }
}

class CarCamera {
  CarCamera({
    required this.lat,
    required this.lon,
    required this.zoom,
    required this.bearing,
    required this.tilt,
    required this.animateMs,
  });

  double lat;

  double lon;

  double zoom;

  double bearing;

  double tilt;

  int animateMs;

  List<Object?> _toList() {
    return <Object?>[lat, lon, zoom, bearing, tilt, animateMs];
  }

  Object encode() {
    return _toList();
  }

  static CarCamera decode(Object result) {
    result as List<Object?>;
    return CarCamera(
      lat: result[0]! as double,
      lon: result[1]! as double,
      zoom: result[2]! as double,
      bearing: result[3]! as double,
      tilt: result[4]! as double,
      animateMs: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarCamera || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(lat, other.lat) &&
        _deepEquals(lon, other.lon) &&
        _deepEquals(zoom, other.zoom) &&
        _deepEquals(bearing, other.bearing) &&
        _deepEquals(tilt, other.tilt) &&
        _deepEquals(animateMs, other.animateMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarCamera(lat: $lat, lon: $lon, zoom: $zoom, bearing: $bearing, tilt: $tilt, animateMs: $animateMs)';
  }
}

class CarBounds {
  CarBounds({
    required this.south,
    required this.west,
    required this.north,
    required this.east,
  });

  double south;

  double west;

  double north;

  double east;

  List<Object?> _toList() {
    return <Object?>[south, west, north, east];
  }

  Object encode() {
    return _toList();
  }

  static CarBounds decode(Object result) {
    result as List<Object?>;
    return CarBounds(
      south: result[0]! as double,
      west: result[1]! as double,
      north: result[2]! as double,
      east: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarBounds || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(south, other.south) &&
        _deepEquals(west, other.west) &&
        _deepEquals(north, other.north) &&
        _deepEquals(east, other.east);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarBounds(south: $south, west: $west, north: $north, east: $east)';
  }
}

/// The car's screen.
class CarSurface {
  CarSurface({
    required this.width,
    required this.height,
    required this.density,
    required this.dark,
    required this.platform,
  });

  double width;

  double height;

  double density;

  bool dark;

  /// `androidauto` or `carplay`.
  String platform;

  List<Object?> _toList() {
    return <Object?>[width, height, density, dark, platform];
  }

  Object encode() {
    return _toList();
  }

  static CarSurface decode(Object result) {
    result as List<Object?>;
    return CarSurface(
      width: result[0]! as double,
      height: result[1]! as double,
      density: result[2]! as double,
      dark: result[3]! as bool,
      platform: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarSurface || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(density, other.density) &&
        _deepEquals(dark, other.dark) &&
        _deepEquals(platform, other.platform);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarSurface(width: $width, height: $height, density: $density, dark: $dark, platform: $platform)';
  }
}

/// A question to the driver, like a faster route.
class CarAlert {
  CarAlert({
    required this.id,
    required this.title,
    required this.text,
    required this.accept,
    required this.reject,
    required this.seconds,
  });

  String id;

  String title;

  String text;

  String accept;

  String reject;

  /// After this it disappears by itself.
  int seconds;

  List<Object?> _toList() {
    return <Object?>[id, title, text, accept, reject, seconds];
  }

  Object encode() {
    return _toList();
  }

  static CarAlert decode(Object result) {
    result as List<Object?>;
    return CarAlert(
      id: result[0]! as String,
      title: result[1]! as String,
      text: result[2]! as String,
      accept: result[3]! as String,
      reject: result[4]! as String,
      seconds: result[5]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CarAlert || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(title, other.title) &&
        _deepEquals(text, other.text) &&
        _deepEquals(accept, other.accept) &&
        _deepEquals(reject, other.reject) &&
        _deepEquals(seconds, other.seconds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CarAlert(id: $id, title: $title, text: $text, accept: $accept, reject: $reject, seconds: $seconds)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CarManeuverType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is CarPlace) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is CarRouteSummary) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is CarRoadSign) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is CarLane) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is CarManeuver) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is CarTrip) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is CarSpeed) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is CarPosition) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is CarCamera) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is CarBounds) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is CarSurface) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is CarAlert) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : CarManeuverType.values[value];
      case 130:
        return CarPlace.decode(readValue(buffer)!);
      case 131:
        return CarRouteSummary.decode(readValue(buffer)!);
      case 132:
        return CarRoadSign.decode(readValue(buffer)!);
      case 133:
        return CarLane.decode(readValue(buffer)!);
      case 134:
        return CarManeuver.decode(readValue(buffer)!);
      case 135:
        return CarTrip.decode(readValue(buffer)!);
      case 136:
        return CarSpeed.decode(readValue(buffer)!);
      case 137:
        return CarPosition.decode(readValue(buffer)!);
      case 138:
        return CarCamera.decode(readValue(buffer)!);
      case 139:
        return CarBounds.decode(readValue(buffer)!);
      case 140:
        return CarSurface.decode(readValue(buffer)!);
      case 141:
        return CarAlert.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Dart to the car. Native ignores everything while no car is connected.
class CarHostApi {
  /// Constructor for [CarHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CarHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Dart's handlers are in place; native replays a connection that happened
  /// before this.
  Future<void> ready() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.ready$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// The labels of the templates in the user's language, by key (see
  /// `CarBridge.texts`), so the translations stay in one place.
  Future<void> setTexts(Map<String, String> texts) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.setTexts$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[texts],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// The map style: a URL, or the style itself as JSON (the night version).
  Future<void> setStyle(String style, bool isJson) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.setStyle$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[style, isJson],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// A PNG for the map (arrow head, location dot) or the templates (maneuver
  /// and lane icons), by key. [scale] is the pixel ratio it was drawn at.
  Future<void> registerImage(String key, Uint8List png, double scale) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.registerImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, png, scale],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// GeoJSON feature collections, as the phone draws them.
  Future<void> setRoutes(String geoJson) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.setRoutes$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[geoJson],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setDriven(String geoJson) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.setDriven$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[geoJson],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setArrow(String geoJson) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.setArrow$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[geoJson],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setPosition(CarPosition position) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.setPosition$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[position],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// The camera during navigation: over the position, in the direction of
  /// travel.
  Future<void> followCamera(CarCamera camera) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.followCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[camera],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> fitBounds(CarBounds bounds, double paddingPx) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.fitBounds$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[bounds, paddingPx],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Whether the camera follows; off after the user moved the map.
  Future<void> setFollowing(bool following) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.setFollowing$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[following],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// The start screen: pick where to go. [locationOk]: the phone has a fix;
  /// otherwise the car asks for permission or tells the driver to open the
  /// app.
  Future<void> showHome(
    List<CarPlace> favourites,
    List<CarPlace> recents,
    bool locationOk,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.showHome$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[favourites, recents, locationOk],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// The routes to choose from, after a place was picked.
  Future<void> showRoutePreview(
    String destinationLabel,
    List<CarRouteSummary> routes,
    int chosen,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.showRoutePreview$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[destinationLabel, routes, chosen],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> showLoading(bool loading) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.showLoading$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[loading],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> showMessage(String title, String text) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.showMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[title, text],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> startNavigation(CarTrip trip) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.startNavigation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[trip],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> updateManeuver(
    CarManeuver next,
    CarTrip trip,
    CarSpeed speed,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.updateManeuver$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[next, trip, speed],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setRecalculating(bool recalculating) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.setRecalculating$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[recalculating],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> showArrived(String destinationLabel) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.showArrived$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[destinationLabel],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> endNavigation() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.endNavigation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setMuted(bool muted) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.setMuted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[muted],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> showAlert(CarAlert alert) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.showAlert$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[alert],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> dismissAlert(String id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.homemaps.CarHostApi.dismissAlert$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// The car to Dart: what the driver does.
abstract class CarFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void connected(CarSurface surface);

  void disconnected();

  /// The screen size or dark mode changed.
  void surfaceChanged(CarSurface surface);

  void placeChosen(String id);

  Future<List<CarPlace>> search(String text);

  void routeChosen(int index);

  void startTrip();

  void stopTrip();

  void toggleMute();

  /// The driver panned or zoomed: following stops.
  void userMovedMap();

  void recenter();

  void alertAnswered(String id, bool accepted);

  /// Android's test drive (the review requires it): a fake GPS drives the
  /// route.
  void autoDriveEnabled();

  /// A `geo:` or navigation intent in the car: a point with a name, or a
  /// search text.
  void navigateTo(double? lat, double? lon, String? label, String? query);

  void backToHome();

  static void setUp(
    CarFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.connected$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CarSurface arg_surface = args[0]! as CarSurface;
          try {
            api.connected(arg_surface);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.disconnected$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.disconnected();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.surfaceChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final CarSurface arg_surface = args[0]! as CarSurface;
          try {
            api.surfaceChanged(arg_surface);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.placeChosen$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_id = args[0]! as String;
          try {
            api.placeChosen(arg_id);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.search$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_text = args[0]! as String;
          try {
            final List<CarPlace> output = await api.search(arg_text);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.routeChosen$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final int arg_index = args[0]! as int;
          try {
            api.routeChosen(arg_index);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.startTrip$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.startTrip();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.stopTrip$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.stopTrip();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.toggleMute$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.toggleMute();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.userMovedMap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.userMovedMap();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.recenter$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.recenter();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.alertAnswered$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_id = args[0]! as String;
          final bool arg_accepted = args[1]! as bool;
          try {
            api.alertAnswered(arg_id, arg_accepted);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.autoDriveEnabled$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.autoDriveEnabled();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.navigateTo$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final double? arg_lat = args[0] as double?;
          final double? arg_lon = args[1] as double?;
          final String? arg_label = args[2] as String?;
          final String? arg_query = args[3] as String?;
          try {
            api.navigateTo(arg_lat, arg_lon, arg_label, arg_query);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.homemaps.CarFlutterApi.backToHome$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.backToHome();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
