// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum CarApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// What the maneuver is, grouped like the phone's icons. Native maps this to
/// its own maneuver type; the icon itself comes from Dart (see registerImage).
enum CarManeuverType: Int, CaseIterable {
  case depart = 0
  case destination = 1
  case destinationLeft = 2
  case destinationRight = 3
  case straight = 4
  case nameChange = 5
  case slightRight = 6
  case right = 7
  case sharpRight = 8
  case uturnRight = 9
  case uturnLeft = 10
  case sharpLeft = 11
  case left = 12
  case slightLeft = 13
  case onRampStraight = 14
  case onRampRight = 15
  case onRampLeft = 16
  case offRampRight = 17
  case offRampLeft = 18
  case keepStraight = 19
  case keepRight = 20
  case keepLeft = 21
  case merge = 22
  case mergeRight = 23
  case mergeLeft = 24
  case roundabout = 25
  case roundaboutExit = 26
  case ferryEnter = 27
  case ferryExit = 28
}

/// A destination to pick: home, work, a recent one or a search result.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CarPlace: Hashable, CustomStringConvertible {
  /// Dart's key for [CarFlutterApi.placeChosen].
  var id: String
  var label: String
  var detail: String
  var lat: Double
  var lon: Double
  /// `home`, `work`, `recent` or `search`.
  var kind: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarPlace? {
    let id = pigeonVar_list[0] as! String
    let label = pigeonVar_list[1] as! String
    let detail = pigeonVar_list[2] as! String
    let lat = pigeonVar_list[3] as! Double
    let lon = pigeonVar_list[4] as! Double
    let kind = pigeonVar_list[5] as! String

    return CarPlace(
      id: id,
      label: label,
      detail: detail,
      lat: lat,
      lon: lon,
      kind: kind
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      label,
      detail,
      lat,
      lon,
      kind,
    ]
  }
  static func == (lhs: CarPlace, rhs: CarPlace) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.id, rhs.id) && CarApiPigeonInternal.deepEquals(lhs.label, rhs.label) && CarApiPigeonInternal.deepEquals(lhs.detail, rhs.detail) && CarApiPigeonInternal.deepEquals(lhs.lat, rhs.lat) && CarApiPigeonInternal.deepEquals(lhs.lon, rhs.lon) && CarApiPigeonInternal.deepEquals(lhs.kind, rhs.kind)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarPlace")
    CarApiPigeonInternal.deepHash(value: id, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: label, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: detail, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: lat, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: lon, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: kind, hasher: &hasher)
  }

  public var description: String {
    return "CarPlace(id: \(String(describing: id)), label: \(String(describing: label)), detail: \(String(describing: detail)), lat: \(String(describing: lat)), lon: \(String(describing: lon)), kind: \(String(describing: kind)))"
  }
}

/// One route to choose from in the preview.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CarRouteSummary: Hashable, CustomStringConvertible {
  var index: Int64
  /// "via A12, A27", or empty.
  var via: String
  var meters: Double
  var seconds: Double
  /// Extra time because of traffic, 0 if none.
  var delaySeconds: Double
  var hasToll: Bool
  var hasFerry: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarRouteSummary? {
    let index = pigeonVar_list[0] as! Int64
    let via = pigeonVar_list[1] as! String
    let meters = pigeonVar_list[2] as! Double
    let seconds = pigeonVar_list[3] as! Double
    let delaySeconds = pigeonVar_list[4] as! Double
    let hasToll = pigeonVar_list[5] as! Bool
    let hasFerry = pigeonVar_list[6] as! Bool

    return CarRouteSummary(
      index: index,
      via: via,
      meters: meters,
      seconds: seconds,
      delaySeconds: delaySeconds,
      hasToll: hasToll,
      hasFerry: hasFerry
    )
  }
  func toList() -> [Any?] {
    return [
      index,
      via,
      meters,
      seconds,
      delaySeconds,
      hasToll,
      hasFerry,
    ]
  }
  static func == (lhs: CarRouteSummary, rhs: CarRouteSummary) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.index, rhs.index) && CarApiPigeonInternal.deepEquals(lhs.via, rhs.via) && CarApiPigeonInternal.deepEquals(lhs.meters, rhs.meters) && CarApiPigeonInternal.deepEquals(lhs.seconds, rhs.seconds) && CarApiPigeonInternal.deepEquals(lhs.delaySeconds, rhs.delaySeconds) && CarApiPigeonInternal.deepEquals(lhs.hasToll, rhs.hasToll) && CarApiPigeonInternal.deepEquals(lhs.hasFerry, rhs.hasFerry)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarRouteSummary")
    CarApiPigeonInternal.deepHash(value: index, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: via, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: meters, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: seconds, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: delaySeconds, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: hasToll, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: hasFerry, hasher: &hasher)
  }

  public var description: String {
    return "CarRouteSummary(index: \(String(describing: index)), via: \(String(describing: via)), meters: \(String(describing: meters)), seconds: \(String(describing: seconds)), delaySeconds: \(String(describing: delaySeconds)), hasToll: \(String(describing: hasToll)), hasFerry: \(String(describing: hasFerry)))"
  }
}

/// The sign at an exit: number, road numbers and directions.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CarRoadSign: Hashable, CustomStringConvertible {
  var exit: String? = nil
  var roads: [String]
  var directions: [String]
  var label: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarRoadSign? {
    let exit: String? = nilOrValue(pigeonVar_list[0])
    let roads = pigeonVar_list[1] as! [String]
    let directions = pigeonVar_list[2] as! [String]
    let label: String? = nilOrValue(pigeonVar_list[3])

    return CarRoadSign(
      exit: exit,
      roads: roads,
      directions: directions,
      label: label
    )
  }
  func toList() -> [Any?] {
    return [
      exit,
      roads,
      directions,
      label,
    ]
  }
  static func == (lhs: CarRoadSign, rhs: CarRoadSign) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.exit, rhs.exit) && CarApiPigeonInternal.deepEquals(lhs.roads, rhs.roads) && CarApiPigeonInternal.deepEquals(lhs.directions, rhs.directions) && CarApiPigeonInternal.deepEquals(lhs.label, rhs.label)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarRoadSign")
    CarApiPigeonInternal.deepHash(value: exit, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: roads, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: directions, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: label, hasher: &hasher)
  }

  public var description: String {
    return "CarRoadSign(exit: \(String(describing: exit)), roads: \(String(describing: roads)), directions: \(String(describing: directions)), label: \(String(describing: label)))"
  }
}

/// One lane, as OSRM names the directions ("left", "slight right", ...).
///
/// Generated class from Pigeon that represents data sent in messages.
struct CarLane: Hashable, CustomStringConvertible {
  var directions: [String]
  /// This lane is one you can use for the maneuver.
  var correct: Bool
  /// The direction you take in this lane, if it is a correct one.
  var usage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarLane? {
    let directions = pigeonVar_list[0] as! [String]
    let correct = pigeonVar_list[1] as! Bool
    let usage: String? = nilOrValue(pigeonVar_list[2])

    return CarLane(
      directions: directions,
      correct: correct,
      usage: usage
    )
  }
  func toList() -> [Any?] {
    return [
      directions,
      correct,
      usage,
    ]
  }
  static func == (lhs: CarLane, rhs: CarLane) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.directions, rhs.directions) && CarApiPigeonInternal.deepEquals(lhs.correct, rhs.correct) && CarApiPigeonInternal.deepEquals(lhs.usage, rhs.usage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarLane")
    CarApiPigeonInternal.deepHash(value: directions, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: correct, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: usage, hasher: &hasher)
  }

  public var description: String {
    return "CarLane(directions: \(String(describing: directions)), correct: \(String(describing: correct)), usage: \(String(describing: usage)))"
  }
}

/// The next maneuver, as the car shows it.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CarManeuver: Hashable, CustomStringConvertible {
  var type: CarManeuverType
  /// The full sentence ("Turn right onto Main Street").
  var instruction: String
  /// Briefly what you do at a ramp or fork ("Keep left"), or null.
  var shortAction: String? = nil
  var streets: [String]
  var roundaboutExit: Int64? = nil
  /// Where you leave the roundabout, clockwise from straight on (degrees).
  var roundaboutAngle: Double? = nil
  var sign: CarRoadSign? = nil
  /// An image registered earlier with [CarHostApi.registerImage].
  var iconKey: String
  /// Already rounded so it doesn't change every meter.
  var metersToNext: Double
  /// The maneuver right after this one, if it follows within a few hundred
  /// meters: at most one. (A list, not a nullable field: Swift structs can't
  /// contain themselves.)
  var then: [CarManeuver]
  var lanes: [CarLane]? = nil
  /// The lane bar as an image, registered earlier.
  var lanesIconKey: String? = nil
  /// How far the lanes' junction is, if that isn't the maneuver itself.
  var lanesAhead: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarManeuver? {
    let type = pigeonVar_list[0] as! CarManeuverType
    let instruction = pigeonVar_list[1] as! String
    let shortAction: String? = nilOrValue(pigeonVar_list[2])
    let streets = pigeonVar_list[3] as! [String]
    let roundaboutExit: Int64? = nilOrValue(pigeonVar_list[4])
    let roundaboutAngle: Double? = nilOrValue(pigeonVar_list[5])
    let sign: CarRoadSign? = nilOrValue(pigeonVar_list[6])
    let iconKey = pigeonVar_list[7] as! String
    let metersToNext = pigeonVar_list[8] as! Double
    let then = pigeonVar_list[9] as! [CarManeuver]
    let lanes: [CarLane]? = nilOrValue(pigeonVar_list[10])
    let lanesIconKey: String? = nilOrValue(pigeonVar_list[11])
    let lanesAhead: Double? = nilOrValue(pigeonVar_list[12])

    return CarManeuver(
      type: type,
      instruction: instruction,
      shortAction: shortAction,
      streets: streets,
      roundaboutExit: roundaboutExit,
      roundaboutAngle: roundaboutAngle,
      sign: sign,
      iconKey: iconKey,
      metersToNext: metersToNext,
      then: then,
      lanes: lanes,
      lanesIconKey: lanesIconKey,
      lanesAhead: lanesAhead
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      instruction,
      shortAction,
      streets,
      roundaboutExit,
      roundaboutAngle,
      sign,
      iconKey,
      metersToNext,
      then,
      lanes,
      lanesIconKey,
      lanesAhead,
    ]
  }
  static func == (lhs: CarManeuver, rhs: CarManeuver) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.type, rhs.type) && CarApiPigeonInternal.deepEquals(lhs.instruction, rhs.instruction) && CarApiPigeonInternal.deepEquals(lhs.shortAction, rhs.shortAction) && CarApiPigeonInternal.deepEquals(lhs.streets, rhs.streets) && CarApiPigeonInternal.deepEquals(lhs.roundaboutExit, rhs.roundaboutExit) && CarApiPigeonInternal.deepEquals(lhs.roundaboutAngle, rhs.roundaboutAngle) && CarApiPigeonInternal.deepEquals(lhs.sign, rhs.sign) && CarApiPigeonInternal.deepEquals(lhs.iconKey, rhs.iconKey) && CarApiPigeonInternal.deepEquals(lhs.metersToNext, rhs.metersToNext) && CarApiPigeonInternal.deepEquals(lhs.then, rhs.then) && CarApiPigeonInternal.deepEquals(lhs.lanes, rhs.lanes) && CarApiPigeonInternal.deepEquals(lhs.lanesIconKey, rhs.lanesIconKey) && CarApiPigeonInternal.deepEquals(lhs.lanesAhead, rhs.lanesAhead)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarManeuver")
    CarApiPigeonInternal.deepHash(value: type, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: instruction, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: shortAction, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: streets, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: roundaboutExit, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: roundaboutAngle, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: sign, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: iconKey, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: metersToNext, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: then, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: lanes, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: lanesIconKey, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: lanesAhead, hasher: &hasher)
  }

  public var description: String {
    return "CarManeuver(type: \(String(describing: type)), instruction: \(String(describing: instruction)), shortAction: \(String(describing: shortAction)), streets: \(String(describing: streets)), roundaboutExit: \(String(describing: roundaboutExit)), roundaboutAngle: \(String(describing: roundaboutAngle)), sign: \(String(describing: sign)), iconKey: \(String(describing: iconKey)), metersToNext: \(String(describing: metersToNext)), then: \(String(describing: then)), lanes: \(String(describing: lanes)), lanesIconKey: \(String(describing: lanesIconKey)), lanesAhead: \(String(describing: lanesAhead)))"
  }
}

/// The trip as a whole: where to, how far, how long.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CarTrip: Hashable, CustomStringConvertible {
  var destinationLabel: String
  var remainingMeters: Double
  var remainingSeconds: Double
  var etaEpochMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarTrip? {
    let destinationLabel = pigeonVar_list[0] as! String
    let remainingMeters = pigeonVar_list[1] as! Double
    let remainingSeconds = pigeonVar_list[2] as! Double
    let etaEpochMs = pigeonVar_list[3] as! Int64

    return CarTrip(
      destinationLabel: destinationLabel,
      remainingMeters: remainingMeters,
      remainingSeconds: remainingSeconds,
      etaEpochMs: etaEpochMs
    )
  }
  func toList() -> [Any?] {
    return [
      destinationLabel,
      remainingMeters,
      remainingSeconds,
      etaEpochMs,
    ]
  }
  static func == (lhs: CarTrip, rhs: CarTrip) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.destinationLabel, rhs.destinationLabel) && CarApiPigeonInternal.deepEquals(lhs.remainingMeters, rhs.remainingMeters) && CarApiPigeonInternal.deepEquals(lhs.remainingSeconds, rhs.remainingSeconds) && CarApiPigeonInternal.deepEquals(lhs.etaEpochMs, rhs.etaEpochMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarTrip")
    CarApiPigeonInternal.deepHash(value: destinationLabel, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: remainingMeters, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: remainingSeconds, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: etaEpochMs, hasher: &hasher)
  }

  public var description: String {
    return "CarTrip(destinationLabel: \(String(describing: destinationLabel)), remainingMeters: \(String(describing: remainingMeters)), remainingSeconds: \(String(describing: remainingSeconds)), etaEpochMs: \(String(describing: etaEpochMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CarSpeed: Hashable, CustomStringConvertible {
  var limitKmh: Int64? = nil
  /// `osm`, `timeOfDay`, `roadworks` or `msi` (a red ring).
  var limitSource: String
  var speedMs: Double? = nil
  /// Above the speed limit: the next speed camera or the average speed check
  /// you're in. The icon (see [CarHostApi.registerImage]) and its text ("400
  /// m", "avg 97"), with a smaller line below ("2.3 km to go"); null if
  /// there's none.
  var cameraIconKey: String? = nil
  var cameraText: String? = nil
  var cameraDetail: String? = nil
  /// Your average in the section is above its limit: the sign goes red.
  var cameraOver: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarSpeed? {
    let limitKmh: Int64? = nilOrValue(pigeonVar_list[0])
    let limitSource = pigeonVar_list[1] as! String
    let speedMs: Double? = nilOrValue(pigeonVar_list[2])
    let cameraIconKey: String? = nilOrValue(pigeonVar_list[3])
    let cameraText: String? = nilOrValue(pigeonVar_list[4])
    let cameraDetail: String? = nilOrValue(pigeonVar_list[5])
    let cameraOver = pigeonVar_list[6] as! Bool

    return CarSpeed(
      limitKmh: limitKmh,
      limitSource: limitSource,
      speedMs: speedMs,
      cameraIconKey: cameraIconKey,
      cameraText: cameraText,
      cameraDetail: cameraDetail,
      cameraOver: cameraOver
    )
  }
  func toList() -> [Any?] {
    return [
      limitKmh,
      limitSource,
      speedMs,
      cameraIconKey,
      cameraText,
      cameraDetail,
      cameraOver,
    ]
  }
  static func == (lhs: CarSpeed, rhs: CarSpeed) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.limitKmh, rhs.limitKmh) && CarApiPigeonInternal.deepEquals(lhs.limitSource, rhs.limitSource) && CarApiPigeonInternal.deepEquals(lhs.speedMs, rhs.speedMs) && CarApiPigeonInternal.deepEquals(lhs.cameraIconKey, rhs.cameraIconKey) && CarApiPigeonInternal.deepEquals(lhs.cameraText, rhs.cameraText) && CarApiPigeonInternal.deepEquals(lhs.cameraDetail, rhs.cameraDetail) && CarApiPigeonInternal.deepEquals(lhs.cameraOver, rhs.cameraOver)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarSpeed")
    CarApiPigeonInternal.deepHash(value: limitKmh, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: limitSource, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: speedMs, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: cameraIconKey, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: cameraText, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: cameraDetail, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: cameraOver, hasher: &hasher)
  }

  public var description: String {
    return "CarSpeed(limitKmh: \(String(describing: limitKmh)), limitSource: \(String(describing: limitSource)), speedMs: \(String(describing: speedMs)), cameraIconKey: \(String(describing: cameraIconKey)), cameraText: \(String(describing: cameraText)), cameraDetail: \(String(describing: cameraDetail)), cameraOver: \(String(describing: cameraOver)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CarPosition: Hashable, CustomStringConvertible {
  var lat: Double
  var lon: Double
  var heading: Double? = nil
  var speed: Double? = nil
  var accuracy: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarPosition? {
    let lat = pigeonVar_list[0] as! Double
    let lon = pigeonVar_list[1] as! Double
    let heading: Double? = nilOrValue(pigeonVar_list[2])
    let speed: Double? = nilOrValue(pigeonVar_list[3])
    let accuracy = pigeonVar_list[4] as! Double

    return CarPosition(
      lat: lat,
      lon: lon,
      heading: heading,
      speed: speed,
      accuracy: accuracy
    )
  }
  func toList() -> [Any?] {
    return [
      lat,
      lon,
      heading,
      speed,
      accuracy,
    ]
  }
  static func == (lhs: CarPosition, rhs: CarPosition) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.lat, rhs.lat) && CarApiPigeonInternal.deepEquals(lhs.lon, rhs.lon) && CarApiPigeonInternal.deepEquals(lhs.heading, rhs.heading) && CarApiPigeonInternal.deepEquals(lhs.speed, rhs.speed) && CarApiPigeonInternal.deepEquals(lhs.accuracy, rhs.accuracy)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarPosition")
    CarApiPigeonInternal.deepHash(value: lat, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: lon, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: heading, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: speed, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: accuracy, hasher: &hasher)
  }

  public var description: String {
    return "CarPosition(lat: \(String(describing: lat)), lon: \(String(describing: lon)), heading: \(String(describing: heading)), speed: \(String(describing: speed)), accuracy: \(String(describing: accuracy)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CarCamera: Hashable, CustomStringConvertible {
  var lat: Double
  var lon: Double
  var zoom: Double
  var bearing: Double
  var tilt: Double
  var animateMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarCamera? {
    let lat = pigeonVar_list[0] as! Double
    let lon = pigeonVar_list[1] as! Double
    let zoom = pigeonVar_list[2] as! Double
    let bearing = pigeonVar_list[3] as! Double
    let tilt = pigeonVar_list[4] as! Double
    let animateMs = pigeonVar_list[5] as! Int64

    return CarCamera(
      lat: lat,
      lon: lon,
      zoom: zoom,
      bearing: bearing,
      tilt: tilt,
      animateMs: animateMs
    )
  }
  func toList() -> [Any?] {
    return [
      lat,
      lon,
      zoom,
      bearing,
      tilt,
      animateMs,
    ]
  }
  static func == (lhs: CarCamera, rhs: CarCamera) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.lat, rhs.lat) && CarApiPigeonInternal.deepEquals(lhs.lon, rhs.lon) && CarApiPigeonInternal.deepEquals(lhs.zoom, rhs.zoom) && CarApiPigeonInternal.deepEquals(lhs.bearing, rhs.bearing) && CarApiPigeonInternal.deepEquals(lhs.tilt, rhs.tilt) && CarApiPigeonInternal.deepEquals(lhs.animateMs, rhs.animateMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarCamera")
    CarApiPigeonInternal.deepHash(value: lat, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: lon, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: zoom, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: bearing, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: tilt, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: animateMs, hasher: &hasher)
  }

  public var description: String {
    return "CarCamera(lat: \(String(describing: lat)), lon: \(String(describing: lon)), zoom: \(String(describing: zoom)), bearing: \(String(describing: bearing)), tilt: \(String(describing: tilt)), animateMs: \(String(describing: animateMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CarBounds: Hashable, CustomStringConvertible {
  var south: Double
  var west: Double
  var north: Double
  var east: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarBounds? {
    let south = pigeonVar_list[0] as! Double
    let west = pigeonVar_list[1] as! Double
    let north = pigeonVar_list[2] as! Double
    let east = pigeonVar_list[3] as! Double

    return CarBounds(
      south: south,
      west: west,
      north: north,
      east: east
    )
  }
  func toList() -> [Any?] {
    return [
      south,
      west,
      north,
      east,
    ]
  }
  static func == (lhs: CarBounds, rhs: CarBounds) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.south, rhs.south) && CarApiPigeonInternal.deepEquals(lhs.west, rhs.west) && CarApiPigeonInternal.deepEquals(lhs.north, rhs.north) && CarApiPigeonInternal.deepEquals(lhs.east, rhs.east)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarBounds")
    CarApiPigeonInternal.deepHash(value: south, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: west, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: north, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: east, hasher: &hasher)
  }

  public var description: String {
    return "CarBounds(south: \(String(describing: south)), west: \(String(describing: west)), north: \(String(describing: north)), east: \(String(describing: east)))"
  }
}

/// The car's screen.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CarSurface: Hashable, CustomStringConvertible {
  var width: Double
  var height: Double
  var density: Double
  var dark: Bool
  /// `androidauto` or `carplay`.
  var platform: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarSurface? {
    let width = pigeonVar_list[0] as! Double
    let height = pigeonVar_list[1] as! Double
    let density = pigeonVar_list[2] as! Double
    let dark = pigeonVar_list[3] as! Bool
    let platform = pigeonVar_list[4] as! String

    return CarSurface(
      width: width,
      height: height,
      density: density,
      dark: dark,
      platform: platform
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      density,
      dark,
      platform,
    ]
  }
  static func == (lhs: CarSurface, rhs: CarSurface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.width, rhs.width) && CarApiPigeonInternal.deepEquals(lhs.height, rhs.height) && CarApiPigeonInternal.deepEquals(lhs.density, rhs.density) && CarApiPigeonInternal.deepEquals(lhs.dark, rhs.dark) && CarApiPigeonInternal.deepEquals(lhs.platform, rhs.platform)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarSurface")
    CarApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: density, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: dark, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: platform, hasher: &hasher)
  }

  public var description: String {
    return "CarSurface(width: \(String(describing: width)), height: \(String(describing: height)), density: \(String(describing: density)), dark: \(String(describing: dark)), platform: \(String(describing: platform)))"
  }
}

/// A question to the driver, like a faster route.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CarAlert: Hashable, CustomStringConvertible {
  var id: String
  var title: String
  var text: String
  var accept: String
  var reject: String
  /// After this it disappears by itself.
  var seconds: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarAlert? {
    let id = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let text = pigeonVar_list[2] as! String
    let accept = pigeonVar_list[3] as! String
    let reject = pigeonVar_list[4] as! String
    let seconds = pigeonVar_list[5] as! Int64

    return CarAlert(
      id: id,
      title: title,
      text: text,
      accept: accept,
      reject: reject,
      seconds: seconds
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      text,
      accept,
      reject,
      seconds,
    ]
  }
  static func == (lhs: CarAlert, rhs: CarAlert) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarApiPigeonInternal.deepEquals(lhs.id, rhs.id) && CarApiPigeonInternal.deepEquals(lhs.title, rhs.title) && CarApiPigeonInternal.deepEquals(lhs.text, rhs.text) && CarApiPigeonInternal.deepEquals(lhs.accept, rhs.accept) && CarApiPigeonInternal.deepEquals(lhs.reject, rhs.reject) && CarApiPigeonInternal.deepEquals(lhs.seconds, rhs.seconds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarAlert")
    CarApiPigeonInternal.deepHash(value: id, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: text, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: accept, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: reject, hasher: &hasher)
    CarApiPigeonInternal.deepHash(value: seconds, hasher: &hasher)
  }

  public var description: String {
    return "CarAlert(id: \(String(describing: id)), title: \(String(describing: title)), text: \(String(describing: text)), accept: \(String(describing: accept)), reject: \(String(describing: reject)), seconds: \(String(describing: seconds)))"
  }
}

private class CarApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CarManeuverType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return CarPlace.fromList(self.readValue() as! [Any?])
    case 131:
      return CarRouteSummary.fromList(self.readValue() as! [Any?])
    case 132:
      return CarRoadSign.fromList(self.readValue() as! [Any?])
    case 133:
      return CarLane.fromList(self.readValue() as! [Any?])
    case 134:
      return CarManeuver.fromList(self.readValue() as! [Any?])
    case 135:
      return CarTrip.fromList(self.readValue() as! [Any?])
    case 136:
      return CarSpeed.fromList(self.readValue() as! [Any?])
    case 137:
      return CarPosition.fromList(self.readValue() as! [Any?])
    case 138:
      return CarCamera.fromList(self.readValue() as! [Any?])
    case 139:
      return CarBounds.fromList(self.readValue() as! [Any?])
    case 140:
      return CarSurface.fromList(self.readValue() as! [Any?])
    case 141:
      return CarAlert.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CarApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CarManeuverType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CarPlace {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CarRouteSummary {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CarRoadSign {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? CarLane {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? CarManeuver {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? CarTrip {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? CarSpeed {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? CarPosition {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? CarCamera {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? CarBounds {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? CarSurface {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? CarAlert {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CarApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CarApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CarApiPigeonCodecWriter(data: data)
  }
}

class CarApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CarApiPigeonCodec(readerWriter: CarApiPigeonCodecReaderWriter())
}

/// Dart to the car. Native ignores everything while no car is connected.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CarHostApi {
  /// Dart's handlers are in place; native replays a connection that happened
  /// before this.
  func ready() throws
  /// The labels of the templates in the user's language, by key (see
  /// `CarBridge.texts`), so the translations stay in one place.
  func setTexts(texts: [String: String]) throws
  /// The map style: a URL, or the style itself as JSON (the night version).
  func setStyle(style: String, isJson: Bool) throws
  /// A PNG for the map (arrow head, location dot) or the templates (maneuver
  /// and lane icons), by key. [scale] is the pixel ratio it was drawn at.
  func registerImage(key: String, png: FlutterStandardTypedData, scale: Double) throws
  /// GeoJSON feature collections, as the phone draws them.
  func setRoutes(geoJson: String) throws
  func setDriven(geoJson: String) throws
  func setArrow(geoJson: String) throws
  func setPosition(position: CarPosition) throws
  /// The camera during navigation: over the position, in the direction of
  /// travel.
  func followCamera(camera: CarCamera) throws
  func fitBounds(bounds: CarBounds, paddingPx: Double) throws
  /// Whether the camera follows; off after the user moved the map.
  func setFollowing(following: Bool) throws
  /// The start screen: pick where to go. [locationOk]: the phone has a fix;
  /// otherwise the car asks for permission or tells the driver to open the
  /// app.
  func showHome(favourites: [CarPlace], recents: [CarPlace], locationOk: Bool) throws
  /// The routes to choose from, after a place was picked.
  func showRoutePreview(destinationLabel: String, routes: [CarRouteSummary], chosen: Int64) throws
  func showLoading(loading: Bool) throws
  func showMessage(title: String, text: String) throws
  func startNavigation(trip: CarTrip) throws
  func updateManeuver(next: CarManeuver, trip: CarTrip, speed: CarSpeed) throws
  func setRecalculating(recalculating: Bool) throws
  func showArrived(destinationLabel: String) throws
  func endNavigation() throws
  func setMuted(muted: Bool) throws
  func showAlert(alert: CarAlert) throws
  func dismissAlert(id: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CarHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CarApiPigeonCodec.shared }
  /// Sets up an instance of `CarHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CarHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Dart's handlers are in place; native replays a connection that happened
    /// before this.
    let readyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.ready\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readyChannel.setMessageHandler { _, reply in
        do {
          try api.ready()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      readyChannel.setMessageHandler(nil)
    }
    /// The labels of the templates in the user's language, by key (see
    /// `CarBridge.texts`), so the translations stay in one place.
    let setTextsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.setTexts\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setTextsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textsArg = args[0] as! [String: String]
        do {
          try api.setTexts(texts: textsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setTextsChannel.setMessageHandler(nil)
    }
    /// The map style: a URL, or the style itself as JSON (the night version).
    let setStyleChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.setStyle\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setStyleChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let styleArg = args[0] as! String
        let isJsonArg = args[1] as! Bool
        do {
          try api.setStyle(style: styleArg, isJson: isJsonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setStyleChannel.setMessageHandler(nil)
    }
    /// A PNG for the map (arrow head, location dot) or the templates (maneuver
    /// and lane icons), by key. [scale] is the pixel ratio it was drawn at.
    let registerImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.registerImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let pngArg = args[1] as! FlutterStandardTypedData
        let scaleArg = args[2] as! Double
        do {
          try api.registerImage(key: keyArg, png: pngArg, scale: scaleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      registerImageChannel.setMessageHandler(nil)
    }
    /// GeoJSON feature collections, as the phone draws them.
    let setRoutesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.setRoutes\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRoutesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let geoJsonArg = args[0] as! String
        do {
          try api.setRoutes(geoJson: geoJsonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRoutesChannel.setMessageHandler(nil)
    }
    let setDrivenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.setDriven\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDrivenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let geoJsonArg = args[0] as! String
        do {
          try api.setDriven(geoJson: geoJsonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDrivenChannel.setMessageHandler(nil)
    }
    let setArrowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.setArrow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setArrowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let geoJsonArg = args[0] as! String
        do {
          try api.setArrow(geoJson: geoJsonArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setArrowChannel.setMessageHandler(nil)
    }
    let setPositionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.setPosition\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setPositionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let positionArg = args[0] as! CarPosition
        do {
          try api.setPosition(position: positionArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setPositionChannel.setMessageHandler(nil)
    }
    /// The camera during navigation: over the position, in the direction of
    /// travel.
    let followCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.followCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      followCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cameraArg = args[0] as! CarCamera
        do {
          try api.followCamera(camera: cameraArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      followCameraChannel.setMessageHandler(nil)
    }
    let fitBoundsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.fitBounds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fitBoundsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let boundsArg = args[0] as! CarBounds
        let paddingPxArg = args[1] as! Double
        do {
          try api.fitBounds(bounds: boundsArg, paddingPx: paddingPxArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      fitBoundsChannel.setMessageHandler(nil)
    }
    /// Whether the camera follows; off after the user moved the map.
    let setFollowingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.setFollowing\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setFollowingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let followingArg = args[0] as! Bool
        do {
          try api.setFollowing(following: followingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setFollowingChannel.setMessageHandler(nil)
    }
    /// The start screen: pick where to go. [locationOk]: the phone has a fix;
    /// otherwise the car asks for permission or tells the driver to open the
    /// app.
    let showHomeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.showHome\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showHomeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let favouritesArg = args[0] as! [CarPlace]
        let recentsArg = args[1] as! [CarPlace]
        let locationOkArg = args[2] as! Bool
        do {
          try api.showHome(favourites: favouritesArg, recents: recentsArg, locationOk: locationOkArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showHomeChannel.setMessageHandler(nil)
    }
    /// The routes to choose from, after a place was picked.
    let showRoutePreviewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.showRoutePreview\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showRoutePreviewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationLabelArg = args[0] as! String
        let routesArg = args[1] as! [CarRouteSummary]
        let chosenArg = args[2] as! Int64
        do {
          try api.showRoutePreview(destinationLabel: destinationLabelArg, routes: routesArg, chosen: chosenArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showRoutePreviewChannel.setMessageHandler(nil)
    }
    let showLoadingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.showLoading\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showLoadingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let loadingArg = args[0] as! Bool
        do {
          try api.showLoading(loading: loadingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showLoadingChannel.setMessageHandler(nil)
    }
    let showMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.showMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let titleArg = args[0] as! String
        let textArg = args[1] as! String
        do {
          try api.showMessage(title: titleArg, text: textArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showMessageChannel.setMessageHandler(nil)
    }
    let startNavigationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.startNavigation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startNavigationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tripArg = args[0] as! CarTrip
        do {
          try api.startNavigation(trip: tripArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startNavigationChannel.setMessageHandler(nil)
    }
    let updateManeuverChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.updateManeuver\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateManeuverChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nextArg = args[0] as! CarManeuver
        let tripArg = args[1] as! CarTrip
        let speedArg = args[2] as! CarSpeed
        do {
          try api.updateManeuver(next: nextArg, trip: tripArg, speed: speedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateManeuverChannel.setMessageHandler(nil)
    }
    let setRecalculatingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.setRecalculating\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRecalculatingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recalculatingArg = args[0] as! Bool
        do {
          try api.setRecalculating(recalculating: recalculatingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setRecalculatingChannel.setMessageHandler(nil)
    }
    let showArrivedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.showArrived\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showArrivedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let destinationLabelArg = args[0] as! String
        do {
          try api.showArrived(destinationLabel: destinationLabelArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showArrivedChannel.setMessageHandler(nil)
    }
    let endNavigationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.endNavigation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endNavigationChannel.setMessageHandler { _, reply in
        do {
          try api.endNavigation()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      endNavigationChannel.setMessageHandler(nil)
    }
    let setMutedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.setMuted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setMutedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mutedArg = args[0] as! Bool
        do {
          try api.setMuted(muted: mutedArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setMutedChannel.setMessageHandler(nil)
    }
    let showAlertChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.showAlert\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showAlertChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let alertArg = args[0] as! CarAlert
        do {
          try api.showAlert(alert: alertArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showAlertChannel.setMessageHandler(nil)
    }
    let dismissAlertChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.homemaps.CarHostApi.dismissAlert\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      dismissAlertChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! String
        do {
          try api.dismissAlert(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      dismissAlertChannel.setMessageHandler(nil)
    }
  }
}

/// The car to Dart: what the driver does.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CarFlutterApiProtocol {
  @MainActor func connected(surface surfaceArg: CarSurface) async throws
  @MainActor func disconnected() async throws
  /// The screen size or dark mode changed.
  @MainActor func surfaceChanged(surface surfaceArg: CarSurface) async throws
  @MainActor func placeChosen(id idArg: String) async throws
  @MainActor func search(text textArg: String) async throws -> [CarPlace]
  @MainActor func routeChosen(index indexArg: Int64) async throws
  @MainActor func startTrip() async throws
  @MainActor func stopTrip() async throws
  @MainActor func toggleMute() async throws
  /// The driver panned or zoomed: following stops.
  @MainActor func userMovedMap() async throws
  @MainActor func recenter() async throws
  @MainActor func alertAnswered(id idArg: String, accepted acceptedArg: Bool) async throws
  /// Android's test drive (the review requires it): a fake GPS drives the
  /// route.
  @MainActor func autoDriveEnabled() async throws
  /// A `geo:` or navigation intent in the car: a point with a name, or a
  /// search text.
  @MainActor func navigateTo(lat latArg: Double?, lon lonArg: Double?, label labelArg: String?, query queryArg: String?) async throws
  @MainActor func backToHome() async throws
}
class CarFlutterApi: CarFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CarApiPigeonCodec {
    return CarApiPigeonCodec.shared
  }
  @MainActor func connected(surface surfaceArg: CarSurface) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.connected\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([surfaceArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func disconnected() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.disconnected\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  /// The screen size or dark mode changed.
  @MainActor func surfaceChanged(surface surfaceArg: CarSurface) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.surfaceChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([surfaceArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func placeChosen(id idArg: String) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.placeChosen\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([idArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func search(text textArg: String) async throws -> [CarPlace] {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.search\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([textArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else if listResponse[0] == nil || listResponse[0] is NSNull {
          continuation.resume(throwing: PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: ""))
        } else {
          let result = listResponse[0] as! [CarPlace]
          continuation.resume(returning: result)
        }
      }
    }
  }
  @MainActor func routeChosen(index indexArg: Int64) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.routeChosen\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([indexArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func startTrip() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.startTrip\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func stopTrip() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.stopTrip\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func toggleMute() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.toggleMute\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  /// The driver panned or zoomed: following stops.
  @MainActor func userMovedMap() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.userMovedMap\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func recenter() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.recenter\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func alertAnswered(id idArg: String, accepted acceptedArg: Bool) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.alertAnswered\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([idArg, acceptedArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  /// Android's test drive (the review requires it): a fake GPS drives the
  /// route.
  @MainActor func autoDriveEnabled() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.autoDriveEnabled\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  /// A `geo:` or navigation intent in the car: a point with a name, or a
  /// search text.
  @MainActor func navigateTo(lat latArg: Double?, lon lonArg: Double?, label labelArg: String?, query queryArg: String?) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.navigateTo\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([latArg, lonArg, labelArg, queryArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  @MainActor func backToHome() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.homemaps.CarFlutterApi.backToHome\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
